# Site settings
title: Grupo de Estudos em Bourdieu — <abbr title="Instituto de Filosofia e Ciências Humanas">IFCH</abbr>/<abbr title="Universidade Estadual de Campinas">Unicamp</abbr>
email: gebunicamp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página do Grupo de Estudos em Bourdieu do Instituto de Filosofia e Ciências Humanas da Universidade Estadual de Campinas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gebu.github.io" # the base hostname & protocol for your site
twitter_username: gebunicamp
github_username:  gebu

# Build settings
markdown: kramdown
